workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      vars:
        UNITY_VERSION: "2021.3.0f1"
      unity:
        version: "2021.3.0f1"
    scripts:
      - name: Install dependencies
        script: |
          echo "Dependencies installed automatically by Codemagic"

      - name: Activate Unity
        script: |
          unity-editor --version $UNITY_VERSION -quit -batchmode -nographics -logFile -

      - name: Build Android
        script: |
          unity-editor \
            -projectPath . \
            -quit -batchmode -nographics \
            -buildTarget Android \
            -customBuildTarget Android \
            -customBuildName "LastSpark" \
            -executeMethod BuildScript.BuildAndroid

    artifacts:
      - build/**/*.apk
